#!/usr/bin/env python3
"""Generate the LaTeX drivers and compile everything.

Source of truth is lectures/bodies/lecture_NN.tex (hand-edited) plus the shared
lectures/preamble.tex. This script writes the thin drivers around them:

  lectures/lecture_NN.tex   standalone article, one lecture per PDF
  lectures/lectures_full.tex   the collected book: one title page, ONE master
                               table of contents, continuous pagination,
                               running heads, per-lecture \\chapter

and then runs tectonic over whichever of those you ask for.

  python3 scripts/build_lectures.py            # drivers + full book
  python3 scripts/build_lectures.py --all      # drivers + book + 15 singles
  python3 scripts/build_lectures.py --gen-only # write drivers, don't compile
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEC = os.path.join(ROOT, "lectures")

TITLES = {
    "01": "Въведение. Случайни експерименти, събития и \\texorpdfstring{$\\sigma$}{σ}-алгебри",
    "02": "Аксиоми на вероятността. Дискретна и геометрична вероятност",
    "03": "Условна вероятност, независимост и формула на Бейс",
    "04": "Случайни величини. Индикатори и дискретни случайни величини",
    "05": "Функция на разпределение. Математическо очакване и дисперсия",
    "06": "Пораждащи функции и основни дискретни разпределения",
    "07": "Теорема на Поасон. Хипергеометрично разпределение, ковариация и корелация",
    "08": "Условно математическо очакване. Непрекъснати случайни величини",
    "09": "Непрекъснати разпределения. Гама и хи-квадрат разпределение",
    "10": "Видове сходимост. Неравенство на Чебишов и закони за големите числа",
    "11": "Централна гранична теорема и функции на моментите",
    "12": "Точкови оценки. Максимално правдоподобие и метод на моментите",
    "13": "Доверителни интервали и проверка на хипотези",
    "14": "Линейна регресия",
    "15": "Преговор по комбинаторика и просто случайно блуждаене",
}
NUMS = ["%02d" % i for i in range(1, 16)]

# Plain-text forms for PDF metadata / running heads (no math, no macros):
# \texorpdfstring{<tex>}{<pdf>} collapses to its second argument.
import re as _re
PLAIN = {n: _re.sub(r"\\texorpdfstring\{[^{}]*\}\{([^{}]*)\}", r"\1", t)
         for n, t in TITLES.items()}

AUTOGEN = ("%% AUTO-GENERATED by scripts/build_lectures.py — do not edit.\n"
           "%% Edit lectures/bodies/lecture_%s.tex or lectures/preamble.tex instead.\n")


def standalone(n):
    extra = ("\n\\section*{Организационна бележка}\n"
             "\\input{bodies/exam_note}\n" if n == "14" else "")
    return AUTOGEN % n + r"""\documentclass[11pt]{article}
\usepackage[a4paper, margin=1in]{geometry}
\input{preamble}
%% Match the collected book: its chapter number is the lecture number, while
%% statement and equation counters run continuously within that chapter.
\renewcommand{\thesection}{%(n)s.\arabic{section}}
\renewcommand{\thethm}{%(n)s.\arabic{thm}}
\renewcommand{\theequation}{%(n)s.\arabic{equation}}

\hypersetup{pdftitle={Лекция %(n)s. %(plain)s}}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\itshape Лекция %(n)s}
\fancyhead[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}

\begin{document}

%% Polyglossia installs captions at \begin{document}; localize afterwards.
\renewcommand{\proofname}{Доказателство}

\begin{center}
  {\Large\bfseries Лекция %(n)s.\ }{\Large %(title)s}
\end{center}
\vspace{1.2em}

\input{bodies/lecture_%(nn)s}
%(extra)s

\end{document}
""" % {"n": str(int(n)), "nn": n, "title": TITLES[n], "plain": PLAIN[n],
       "extra": extra}


def full_book():
    chapters = "\n".join(
        "\\chapter{%s}\n\\input{bodies/lecture_%s}\n" % (TITLES[n], n) for n in NUMS
    )
    return ("% AUTO-GENERATED by scripts/build_lectures.py — do not edit.\n"
            "% Edit lectures/bodies/*.tex or lectures/preamble.tex instead.\n"
            + r"""\documentclass[11pt,openany]{report}
\usepackage[a4paper, margin=1in, top=1.1in, bottom=1.1in]{geometry}
\input{preamble}

%% (Caption names are set at the top of the document body — polyglossia installs
%%  its Bulgarian captions at \begin{document} and would overwrite preamble
%%  \renewcommand declarations.)
\numberwithin{thm}{chapter}
\numberwithin{equation}{chapter}

%% Master contents lists lectures and their sections; the PDF bookmark tree
%% still carries the full subsection depth.
\setcounter{tocdepth}{1}
\setcounter{secnumdepth}{2}

\hypersetup{pdftitle={Вероятности и Статистика — лекционни записки}}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\itshape\nouppercase{\leftmark}}
\fancyhead[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\fancypagestyle{plain}{\fancyhf{}\fancyhead[R]{\small\thepage}%
  \renewcommand{\headrulewidth}{0pt}}

\begin{document}

%% Lectures are the chapters of this book.
\renewcommand{\chaptername}{Лекция}
\renewcommand{\proofname}{Доказателство}
\renewcommand{\crosslecture}[2]{\hyperref[#1]{#2}}
\hypersetup{pageanchor=false}

\begin{titlepage}
\centering
\vspace*{5cm}
{\Huge\bfseries Вероятности и Статистика\par}
\vspace{1.2cm}
{\Large Лекционни записки\par}
\vspace{0.5cm}
{\large Специалност „Софтуерно инженерство“, 2021/2022\par}
\vspace{2.5cm}
{\large 15 лекции\par}
\vfill
\end{titlepage}

\hypersetup{pageanchor=true}
\pagenumbering{roman}
\tableofcontents
\input{bodies/frontmatter}
\clearpage
\pagenumbering{arabic}

"""
            + chapters
            + "\n\\end{document}\n")


def main():
    args = sys.argv[1:]
    for n in NUMS:
        open(os.path.join(LEC, "lecture_%s.tex" % n), "w", encoding="utf-8").write(standalone(n))
    open(os.path.join(LEC, "lectures_full.tex"), "w", encoding="utf-8").write(full_book())
    print("wrote 15 standalone drivers + lectures_full.tex")
    if "--gen-only" in args:
        return

    targets = ["lectures_full.tex"]
    if "--all" in args:
        targets += ["lecture_%s.tex" % n for n in NUMS]
    for t in targets:
        print("compiling", t, flush=True)
        r = subprocess.run(["tectonic", "-X", "compile", t], cwd=LEC,
                           capture_output=True, text=True)
        warn = [l for l in r.stderr.splitlines() if "Overfull" in l or "Underfull" in l]
        if r.returncode != 0:
            print(r.stderr[-4000:])
            sys.exit("FAILED: %s" % t)
        print("  ok — %d over/underfull boxes" % len(warn))


if __name__ == "__main__":
    main()
