#!/usr/bin/env python3
"""Generate lectures/bodies/tables.tex — the statistical tables appendix.

Three passages in lectures 13 and 14 say "от таблиците" without the book ever
containing any, and the quantile q_gamma drives every confidence interval and
critical region from lecture 13 on. This emits the three tables those passages
need, computed rather than transcribed:

  Phi(z)                    standard normal CDF, z = 0.00 .. 3.49
  t_{gamma, n}              Student critical values
  chi^2_{gamma, n}          chi-square critical values (both tails, for the
                            variance interval in lecture 13)

    python3 scripts/gen_tables.py && python3 scripts/build_lectures.py
"""
import os

from scipy import stats

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "lectures", "bodies", "tables.tex")

HEAD = r"""% AUTO-GENERATED by scripts/gen_tables.py — do not edit.
\chapter{Статистически таблици}
\label{app:tables}

Таблиците по-долу съдържат стойностите, към които препращат лекции 13 и 14.
Навсякъде $\Phi$ е функцията на разпределение на стандартното нормално
разпределение, а $q_\gamma$ — нейният $\gamma$-квантил по
\crosslecture{def:quantile}{дефиницията от лекция 13}.

\section{Функция на разпределение на \texorpdfstring{$N(0,1)$}{N(0,1)}}

Стойността в ред $z$ и стълб $u$ е $\Phi(z+u)$. За отрицателни аргументи се
използва симетрията $\Phi(-z) = 1 - \Phi(z)$.

{\footnotesize
\setlength{\tabcolsep}{4pt}
\begin{longtable}{c|cccccccccc}
\toprule
$z$ & 0{,}00 & 0{,}01 & 0{,}02 & 0{,}03 & 0{,}04 & 0{,}05 & 0{,}06 & 0{,}07 & 0{,}08 & 0{,}09 \\
\midrule
\endfirsthead
\toprule
$z$ & 0{,}00 & 0{,}01 & 0{,}02 & 0{,}03 & 0{,}04 & 0{,}05 & 0{,}06 & 0{,}07 & 0{,}08 & 0{,}09 \\
\midrule
\endhead
"""

MID_Q = r"""\bottomrule
\end{longtable}
}

\medskip
\noindent
Най-често използваните квантили на $N(0,1)$:

\begin{center}
\small
\begin{tabular}{c|cccccc}
\toprule
$\gamma$ & 0{,}90 & 0{,}95 & 0{,}975 & 0{,}99 & 0{,}995 & 0{,}999 \\
\midrule
$q_\gamma$ & %s \\
\bottomrule
\end{tabular}
\end{center}

\noindent
Двустранен доверителен интервал с ниво $\gamma$ използва $q_{(1+\gamma)/2}$:
за $\gamma = 0{,}95$ това е $q_{0{,}975} = 1{,}96$, а за $\gamma = 0{,}99$ —
$q_{0{,}995} = 2{,}576$.

\section{Разпределение на Стюдънт}

Стойността в ред $n$ и стълб $\gamma$ е $t_{\gamma,n}$: числото, за което
$\mathbb{P}(T \le t_{\gamma,n}) = \gamma$ при $T \sim t(n)$. Последният ред
($n = \infty$) съвпада с квантилите на $N(0,1)$ — вж.\ забележката за
$n \ge 30$ в лекция~14.

{\footnotesize
\begin{longtable}{c|cccccc}
\toprule
$n$ & 0{,}90 & 0{,}95 & 0{,}975 & 0{,}99 & 0{,}995 & 0{,}999 \\
\midrule
\endfirsthead
\toprule
$n$ & 0{,}90 & 0{,}95 & 0{,}975 & 0{,}99 & 0{,}995 & 0{,}999 \\
\midrule
\endhead
"""

MID_C = r"""\bottomrule
\end{longtable}
}

\section{Разпределение хи-квадрат}

Стойността в ред $n$ и стълб $\gamma$ е $\chi^2_{\gamma,n}$, за което
$\mathbb{P}(U \le \chi^2_{\gamma,n}) = \gamma$ при $U \sim \chi^2(n)$.
Доверителният интервал за дисперсията се нуждае от \emph{двата} края, затова
са дадени и малките, и големите нива.

{\footnotesize
\setlength{\tabcolsep}{5pt}
\begin{longtable}{c|cccccc}
\toprule
$n$ & 0{,}005 & 0{,}025 & 0{,}05 & 0{,}95 & 0{,}975 & 0{,}995 \\
\midrule
\endfirsthead
\toprule
$n$ & 0{,}005 & 0{,}025 & 0{,}05 & 0{,}95 & 0{,}975 & 0{,}995 \\
\midrule
\endhead
"""

TAIL = r"""\bottomrule
\end{longtable}
}
"""


def bg(x, d=4):
    """Bulgarian decimal comma, braced so TeX keeps the spacing tight."""
    return ("%.*f" % (d, x)).replace(".", "{,}")


def main():
    rows = []
    z = 0.0
    while z < 3.4999:
        cells = " & ".join(bg(stats.norm.cdf(z + u / 100.0)) for u in range(10))
        rows.append("%s & %s \\\\" % (bg(z, 1), cells))
        z += 0.1
    phi = "\n".join(rows) + "\n"

    levels = [0.90, 0.95, 0.975, 0.99, 0.995, 0.999]
    qrow = " & ".join(bg(stats.norm.ppf(g), 3) for g in levels)

    trows = []
    dfs = list(range(1, 31)) + [40, 60, 120]
    for n in dfs:
        cells = " & ".join(bg(stats.t.ppf(g, n), 3) for g in levels)
        trows.append("%d & %s \\\\" % (n, cells))
    trows.append("$\\infty$ & %s \\\\" % qrow)
    tt = "\n".join(trows) + "\n"

    clev = [0.005, 0.025, 0.05, 0.95, 0.975, 0.995]
    crows = []
    for n in list(range(1, 31)) + [40, 50, 60, 100]:
        cells = " & ".join(bg(stats.chi2.ppf(g, n), 3) for g in clev)
        crows.append("%d & %s \\\\" % (n, cells))
    cc = "\n".join(crows) + "\n"

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEAD + phi + (MID_Q % qrow) + tt + MID_C + cc + TAIL)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
